-- ========================================================
-- State Level Views
-- Purpose: Compare total disease to life expectancy
-- Calculations: weighted total disease by population
-- ========================================================
DROP VIEW IF EXISTS state_disease;

-- ========================================================
-- state_disease: 
--      Weighted Average by total population
--      Grouped by state
-- ========================================================

CREATE VIEW state_disease AS
SELECT 
    StateDesc, 

    -- Health Outcomes (Diseases)
    SUM(CASE WHEN ARTHRITIS IS NOT NULL THEN ARTHRITIS * TotalPopulation END)
        / SUM(CASE WHEN ARTHRITIS IS NOT NULL THEN TotalPopulation END) AS ARTHRITIS,
    SUM(CASE WHEN BPHIGH IS NOT NULL THEN BPHIGH * TotalPopulation END)
        / SUM(CASE WHEN BPHIGH IS NOT NULL THEN TotalPopulation END) AS BPHIGH,
    SUM(CASE WHEN CANCER IS NOT NULL THEN CANCER * TotalPopulation END)
        / SUM(CASE WHEN CANCER IS NOT NULL THEN TotalPopulation END) AS CANCER,
    SUM(CASE WHEN CASTHMA IS NOT NULL THEN CASTHMA * TotalPopulation END)
        / SUM(CASE WHEN CASTHMA IS NOT NULL THEN TotalPopulation END) AS CASTHMA,
    SUM(CASE WHEN CHD IS NOT NULL THEN CHD * TotalPopulation END)
        / SUM(CASE WHEN CHD IS NOT NULL THEN TotalPopulation END) AS CHD,
    SUM(CASE WHEN COPD IS NOT NULL THEN COPD * TotalPopulation END)
        / SUM(CASE WHEN COPD IS NOT NULL THEN TotalPopulation END) AS COPD,
    SUM(CASE WHEN DEPRESSION IS NOT NULL THEN DEPRESSION * TotalPopulation END)
        / SUM(CASE WHEN DEPRESSION IS NOT NULL THEN TotalPopulation END) AS DEPRESSION,
    SUM(CASE WHEN DIABETES IS NOT NULL THEN DIABETES * TotalPopulation END)
        / SUM(CASE WHEN DIABETES IS NOT NULL THEN TotalPopulation END) AS DIABETES,
    SUM(CASE WHEN HIGHCHOL IS NOT NULL THEN HIGHCHOL * TotalPopulation END)
        / SUM(CASE WHEN HIGHCHOL IS NOT NULL THEN TotalPopulation END) AS HIGHCHOL,
    SUM(CASE WHEN OBESITY IS NOT NULL THEN OBESITY * TotalPopulation END)
        / SUM(CASE WHEN OBESITY IS NOT NULL THEN TotalPopulation END) AS OBESITY,
    SUM(CASE WHEN STROKE IS NOT NULL THEN STROKE * TotalPopulation END)
        / SUM(CASE WHEN STROKE IS NOT NULL THEN TotalPopulation END) AS STROKE,              

    -- Lifestyle Risk Factors
    SUM(CASE WHEN BINGE IS NOT NULL THEN BINGE * TotalPopulation END)
        / SUM(CASE WHEN BINGE IS NOT NULL THEN TotalPopulation END) AS BINGE,
    SUM(CASE WHEN CSMOKING IS NOT NULL THEN CSMOKING * TotalPopulation END)
        / SUM(CASE WHEN CSMOKING IS NOT NULL THEN TotalPopulation END) AS CSMOKING,
    SUM(CASE WHEN LPA IS NOT NULL THEN LPA * TotalPopulation END)
        / SUM(CASE WHEN LPA IS NOT NULL THEN TotalPopulation END) AS LPA,  
    SUM(CASE WHEN SLEEP IS NOT NULL THEN SLEEP * TotalPopulation END)
        / SUM(CASE WHEN SLEEP IS NOT NULL THEN TotalPopulation END) AS SLEEP,      

    -- Screening & Prevention
    SUM(CASE WHEN ACCESS2 IS NOT NULL THEN ACCESS2 * TotalPopulation END)
        / SUM(CASE WHEN ACCESS2 IS NOT NULL THEN TotalPopulation END) AS ACCESS2,
    SUM(CASE WHEN BPMED IS NOT NULL THEN BPMED * TotalPopulation END)
        / SUM(CASE WHEN BPMED IS NOT NULL THEN TotalPopulation END) AS BPMED,
    SUM(CASE WHEN CHECKUP IS NOT NULL THEN CHECKUP * TotalPopulation END)
        / SUM(CASE WHEN CHECKUP IS NOT NULL THEN TotalPopulation END) AS CHECKUP,
    SUM(CASE WHEN CHOLSCREEN IS NOT NULL THEN CHOLSCREEN * TotalPopulation END)
        / SUM(CASE WHEN CHOLSCREEN IS NOT NULL THEN TotalPopulation END) AS CHOLSCREEN,
    SUM(CASE WHEN COLON_SCREEN IS NOT NULL THEN COLON_SCREEN * TotalPopulation END)
        / SUM(CASE WHEN COLON_SCREEN IS NOT NULL THEN TotalPopulation END) AS COLON_SCREEN,
    SUM(CASE WHEN DENTAL IS NOT NULL THEN DENTAL * TotalPopulation END)
        / SUM(CASE WHEN DENTAL IS NOT NULL THEN TotalPopulation END) AS DENTAL,
    SUM(CASE WHEN MAMMOUSE IS NOT NULL THEN MAMMOUSE * TotalPopulation END)
        / SUM(CASE WHEN MAMMOUSE IS NOT NULL THEN TotalPopulation END) AS MAMMOUSE,

    -- Health Status
    SUM(CASE WHEN GHLTH IS NOT NULL THEN GHLTH * TotalPopulation END)
        / SUM(CASE WHEN GHLTH IS NOT NULL THEN TotalPopulation END) AS GHLTH,
    SUM(CASE WHEN MHLTH IS NOT NULL THEN MHLTH * TotalPopulation END)
        / SUM(CASE WHEN MHLTH IS NOT NULL THEN TotalPopulation END) AS MHLTH,
    SUM(CASE WHEN PHLTH IS NOT NULL THEN PHLTH * TotalPopulation END)
        / SUM(CASE WHEN PHLTH IS NOT NULL THEN TotalPopulation END) AS PHLTH,

    -- Disabilities
    SUM(CASE WHEN HEARING IS NOT NULL THEN HEARING * TotalPopulation END)
        / SUM(CASE WHEN HEARING IS NOT NULL THEN TotalPopulation END) AS HEARING,
    SUM(CASE WHEN VISION IS NOT NULL THEN VISION * TotalPopulation END)
        / SUM(CASE WHEN VISION IS NOT NULL THEN TotalPopulation END) AS VISION,
    SUM(CASE WHEN COGNITION IS NOT NULL THEN COGNITION * TotalPopulation END)
        / SUM(CASE WHEN COGNITION IS NOT NULL THEN TotalPopulation END) AS COGNITION,
    SUM(CASE WHEN MOBILITY IS NOT NULL THEN MOBILITY * TotalPopulation END)
        / SUM(CASE WHEN MOBILITY IS NOT NULL THEN TotalPopulation END) AS MOBILITY,
    SUM(CASE WHEN SELFCARE IS NOT NULL THEN SELFCARE * TotalPopulation END)
        / SUM(CASE WHEN SELFCARE IS NOT NULL THEN TotalPopulation END) AS SELFCARE,
    SUM(CASE WHEN INDEPLIVE IS NOT NULL THEN INDEPLIVE * TotalPopulation END)
        / SUM(CASE WHEN INDEPLIVE IS NOT NULL THEN TotalPopulation END) AS INDEPLIVE,
    SUM(CASE WHEN DISABILITY IS NOT NULL THEN DISABILITY * TotalPopulation END)
        / SUM(CASE WHEN DISABILITY IS NOT NULL THEN TotalPopulation END) AS DISABILITY,
    SUM(CASE WHEN TEETHLOST IS NOT NULL THEN TEETHLOST * TotalPopulation END)
        / SUM(CASE WHEN TEETHLOST IS NOT NULL THEN TotalPopulation END) AS TEETHLOST,

    -- Social Determinants
    SUM(CASE WHEN LONELINESS IS NOT NULL THEN LONELINESS * TotalPopulation END)
        / SUM(CASE WHEN LONELINESS IS NOT NULL THEN TotalPopulation END) AS LONELINESS,
    SUM(CASE WHEN FOODSTAMP IS NOT NULL THEN FOODSTAMP * TotalPopulation END)
        / SUM(CASE WHEN FOODSTAMP IS NOT NULL THEN TotalPopulation END) AS FOODSTAMP,
    SUM(CASE WHEN FOODINSECU IS NOT NULL THEN FOODINSECU * TotalPopulation END)
        / SUM(CASE WHEN FOODINSECU IS NOT NULL THEN TotalPopulation END) AS FOODINSECU,
    SUM(CASE WHEN HOUSINSECU IS NOT NULL THEN HOUSINSECU * TotalPopulation END)
        / SUM(CASE WHEN HOUSINSECU IS NOT NULL THEN TotalPopulation END) AS HOUSINSECU,
    SUM(CASE WHEN SHUTUTILITY IS NOT NULL THEN SHUTUTILITY * TotalPopulation END)
        / SUM(CASE WHEN SHUTUTILITY IS NOT NULL THEN TotalPopulation END) AS SHUTUTILITY,
    SUM(CASE WHEN LACKTRPT IS NOT NULL THEN LACKTRPT * TotalPopulation END)
        / SUM(CASE WHEN LACKTRPT IS NOT NULL THEN TotalPopulation END) AS LACKTRPT,
    SUM(CASE WHEN EMOTIONSPT IS NOT NULL THEN EMOTIONSPT * TotalPopulation END)
        / SUM(CASE WHEN EMOTIONSPT IS NOT NULL THEN TotalPopulation END) AS EMOTIONSPT

FROM places_clean
GROUP BY StateDesc;