-- =====================================================================
-- Q5: Do social determinants impact health?
-- Analysis of disease burden vs. social determinants
-- =====================================================================
-- =====================================================================
-- 5a: Effect of social determinants on life expectancy
-- 5b: Effect of social determinants on disease burden
-- =====================================================================

SELECT
    State,
    LifeExpectancy,
    -- DiseaseBurden: Average weighted disease burden by population
    ROUND((COALESCE(ARTHRITIS, 0) + COALESCE(BPHIGH, 0) + COALESCE(CANCER, 0) +
    COALESCE(CASTHMA, 0) + COALESCE(CHD, 0) + COALESCE(COPD, 0) + 
    COALESCE(DEPRESSION, 0) + COALESCE(DIABETES, 0) + COALESCE(HIGHCHOL, 0) +
    COALESCE(OBESITY, 0) + COALESCE(STROKE, 0))
    / NULLIF((CASE WHEN ARTHRITIS IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN BPHIGH IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN CANCER IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN CASTHMA IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN CHD IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN COPD IS NOT NULL THEN 1 ELSE 0 END + 
    CASE WHEN DEPRESSION IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN DIABETES IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN HIGHCHOL IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN OBESITY IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN STROKE IS NOT NULL THEN 1 ELSE 0 END), 0), 1) AS DiseaseBurden,
    -- Social: LONELINESS, FOODSTAMP, FOODINSECU, HOUSINSECU, SHUTUTILITY, LACKTRPT, EMOTIONSPT
    ROUND((COALESCE(LONELINESS, 0) + COALESCE(FOODSTAMP, 0) + COALESCE(FOODINSECU, 0) +
    COALESCE(HOUSINSECU, 0) + COALESCE(SHUTUTILITY, 0)+ COALESCE(LACKTRPT, 0)+
    COALESCE(EMOTIONSPT, 0))
    / NULLIF((CASE WHEN LONELINESS IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN FOODSTAMP IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN FOODINSECU IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN HOUSINSECU IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN SHUTUTILITY IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN LACKTRPT IS NOT NULL THEN 1 ELSE 0 END + 
    CASE WHEN EMOTIONSPT IS NOT NULL THEN 1 ELSE 0 END), 0), 1) AS SocialRisk,
    LONELINESS,
    FOODSTAMP,
    FOODINSECU,
    HOUSINSECU,
    SHUTUTILITY,
    LACKTRPT,
    EMOTIONSPT
FROM state_analysis
WHERE DIABETES IS NOT NULL
ORDER BY LifeExpectancy DESC;

