-- Long format disease data for Tableau state explorer

SELECT State, 'BPHIGH' AS Disease, BPHIGH AS Prevalence FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'COPD', COPD FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'STROKE', STROKE FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'CHD', CHD FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'DIABETES', DIABETES FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'ARTHRITIS', ARTHRITIS FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'OBESITY', OBESITY FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'HIGHCHOL', HIGHCHOL FROM state_analysis WHERE DIABETES IS NOT NULL
UNION ALL
SELECT State, 'DEPRESSION', DEPRESSION FROM state_analysis WHERE DIABETES IS NOT NULL;
